# Lineplot Trend

```{r} 
## Zuordnung über group-dataframe. Falls also eine Gruppe nicht geplottet werden soll,
## einfach hier rausnehmen.
trend_3_subset <- trend_3

## hier nur die nehmen, die "- total" in TR_BUNDESLAND enthalten 

crossDiffTotal <- trend_3_subset$plain[grep(pattern = "- total", trend_3_subset$plain$TR_BUNDESLAND),]$id
crossDiffBL <- trend_3_subset$plain[grep(pattern = "- total", trend_3_subset$plain$TR_BUNDESLAND, invert = TRUE),]$id
trend_3_subset$comparisons[trend_3_subset$comparisons$id %in% crossDiffTotal, "comparison"] <- "crossDiffTotal"

trend_3_subset$group <- subset(trend_3_subset$group, trend_3_subset$group$mhg %in% c("einET", "ersteGen", "total"))

trend_3_prepped <- prep_lineplot(
  trend_3_subset,
  parameter = "mean",
  used_comparisons = c("none", "trend", "crossDiffTotal") ## evtl. auch einfach davor filtern?
)

p <- plot_lineplot(trend_3_prepped,
  point_est = "est_comparison_none",
  point_sig = "sig_comparison_crossDiffTotal", ## sig_noTrend_Comp_crossDiff_wholeGroup
  line_est = "est_comparison_none",
  line_sig = "sig_comparison_trend",
  line_se = "se_comparison_none",
  brace_label_est = "est_comparison_trend",
  brace_label_sig = "sig_comparison_trend",
  brace_label_se = "se_comparison_trend",
  brace_label_sig_high = NULL,
  brace_label_sig_bold = "sig_comparison_trend",
  years_lines = list(c(2009, 2015), c(2015, 2022)),
  years_braces = list(c(2009, 2015), c(2015, 2022)),
  subgroup_var = "mhg",
  background_facet = "total",
  background_subgroup = "total",
  facet_var = "TR_BUNDESLAND",
  seperate_plot_var_box = "wholeGroup",
  title_superscripts = NULL,
  plot_settings = plotsettings_lineplot(default_list = lineplot_4x4)
)

# save_plot(p, filename = "/home/nick/Downloads/test.pdf")
# save_plot(p, filename = "C:/Users/hafiznij/Downloads/test.pdf")
```



# Trend Lesen Deutsch


```{r}
dat_prepped <- prep_tablebarplot(trend_3, par = c("mean", "sd"))
dat_prepped <- filter(dat_prepped, mhg %in% c("aohneZWH", "einET"), !str_detect(TR_BUNDESLAND, "- total"))
dat_prepped <- arrange(dat_prepped, TR_BUNDESLAND)

dat_prepped$TR_BUNDESLAND[duplicated(dat_prepped$TR_BUNDESLAND)] <- " "

column_widths_stand <- standardize_column_width(
  column_widths = list(
    p1 = c(0.05, 0.05, rep(0.05, 7), NA),
    p2 = c(rep(0.05, 7), NA)
  ),
  plot_ranges = c(80, 120) # Range of the x-axes of both plots set in 'axis_x_lims'.
)

p_1 <- plot_tablebar(
  dat = dat_prepped,
  bar_est = "est_2015 - 2009_trend_mean",
  bar_label = NULL,
  bar_sig = "sig_2015 - 2009_trend_mean",
  bar_fill = "mhg",
  column_spanners = list(
    "**2009**<sup>a</sup>" = c(3, 4),
    "**2015**<sup>a</sup>" = c(5, 6),
    "**Differenz 2015-2009<sup>a</sup>**" = c(7, 10)
  ),
  headers = list(
    "**Land**",
    " ",
    "*M*",
    "*SD*",
    "*M*",
    "*SD*",
    "M<sub>2015</sub> - M<sub>2009</sub>",
    "*(SE)*",
    "*d*",
    " "
  ),
  columns_table = c(
    "TR_BUNDESLAND",
    "mhg",
    "est_2009_none_mean",
    "est_2009_none_sd",
    "est_2015_none_mean",
    "est_2015_none_sd",
    "est_2015 - 2009_trend_mean",
    "se_2015 - 2009_trend_mean",
    "es_2015 - 2009_trend_mean"
  ),
  columns_table_sig_bold = list(
    NULL,
    NULL,
    "sig_2009_none_mean",
    NULL, "sig_2015_none_mean",
    NULL,
    "sig_2015 - 2009_trend_mean",
    NULL,
    NULL
  ),
  y_axis = "y_axis",
  plot_settings = plotsettings_tablebarplot(
    axis_x_lims = c(-40, 40),
    background_stripes_colour = c(rep(c("white", "white", "#EBFDF3", "#EBFDF3"), 8), "grey", "grey"),
    bar_fill_colour = c("#20D479", "#8DEBBC"),
    columns_alignment = c(0, 0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5),
    columns_width = column_widths_stand$p1,
    headers_alignment = c(0, 0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0),
    default_list = barplot_table_plot_pattern
  )
)

p_2 <- plot_tablebar(
  dat = dat_prepped,
  bar_est = "est_2022 - 2015_trend_mean",
  bar_label = NULL,
  bar_sig = "sig_2022 - 2015_trend_mean",
  bar_fill = "mhg",
  column_spanners = list(
    "**2015**" = c(1, 2),
    "**2022**" = c(3, 4),
    "**Differenz 2022-2015**" = c(5, 8)
  ),
  headers = list(
    "*M*",
    "*SD*",
    "*M*",
    "*SD*",
    "M<sub>2022</sub> - M<sub>2015</sub>",
    "*(SE)*",
    "*d*",
    " "
  ),
  columns_table = c(
    "est_2015_none_mean",
    "est_2015_none_sd",
    "est_2022_none_mean",
    "est_2022_none_sd",
    "est_2022 - 2015_trend_mean",
    "se_2022 - 2015_trend_mean",
    "es_2022 - 2015_trend_mean"
  ),
  columns_table_se = list(NULL, NULL, NULL, NULL, NULL, "se_2015 - 2009_trend_mean", NULL),
  columns_table_sig_bold = list(
    "sig_2015_none_mean",
    NULL,
    "sig_2022_none_mean",
    NULL,
    "sig_2022 - 2015_trend_mean",
    NULL,
    NULL
  ),
  columns_table_sig_high = list(
    "sig_2015_none_mean",
    NULL,
    "sig_2022_none_mean",
    NULL,
    "sig_2022 - 2015_trend_mean",
    NULL,
    NULL
  ),
  y_axis = "y_axis",
  plot_settings = plotsettings_tablebarplot(
    axis_x_lims = c(-60, 60),
    background_stripes_colour = c(rep(c("white", "white", "#EBFDF3", "#EBFDF3"), 8), "grey", "grey"),
    bar_fill_colour = c("#20D479", "#8DEBBC"),
    columns_alignment = c(0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5),
    columns_width = column_widths_stand$p2,
    headers_alignment = c(0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0),
    default_list = barplot_table_plot_pattern
  )
)

example_plot <- combine_plots(list(p_1, p_2))
# save_plot(example_plot, filename = "C:/Users/hafiznij/Downloads/test_table.pdf", width = 320)
# save_plot(example_plot, filename = "/home/nick/Downloads/test_table.pdf", width = 320)
```


```{r}
dat_prepped_crossdiff <- prep_tablebarplot(trend_3, par = c("mean", "sd")) %>%
  filter(comparison == "crossDiff_of_groupDiff") %>%
  select(comparison, TR_BUNDESLAND, parameter, year, est, se, es, sig, mhg) %>%
  pivot_wider(names_from = c(year, comparison, parameter), values_from = c(est, se, es, sig)) %>%
  mutate(y_axis = 1:nrow(.)) %>%
  as.data.frame() %>%
  arrange(TR_BUNDESLAND)
```
